name: Generate Table Of Contents

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Setup
      - name: Checkout Main
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.6

      - name: Setup Node Environment
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      # Build
      - name: Install Dependencies
        run: pnpm i --frozen-lockfile

      # Generate TOC
      - name: Generate Table of Contents
        run: ./scripts/toc.sh
