name: Generate Table Of Contents

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Setup
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      # Build
      - run: yarn install --skip-builds

      # Generate TOC
      - name: Generate Table of Contents
        run: ./scripts/toc.sh
