name: Migrate TheSocialNetwork Database

on:
  push:
    branches:
      - main

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          
      - name: Install dependencies
        run: yarn workspaces focus tsn-server
        
      - name: Deploy Migration
        run: yarn workspace tsn-server deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}