name: Test Packages

on:
  push: {}
  pull_request: {}

jobs:
  test:
    name: Test Sources

    runs-on: macos-12

    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2

      # Build the Library
      - name: Swift Resolve
        run: swift package resolve
      - name: Swift Build
        run: swift build

      # Start Test Server
      - name: Use Node
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Install Server Dependencies
        run: yarn install
      - name: Start Test Server
        run: yarn workspace server start &
      - name: Wait for Server to Start
        run: yarn dlx wait-on http://127.0.0.1:4000/graphql

      # Perform Tests
      - name: Test Package
        run: swift test

      # Cleanup
      - name: Stop Test Server
        run: kill $(jobs -p)
